#!/bin/sh
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/libexec/gnome-settings-daemon >/dev/null; then
#  /usr/libexec/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager 
#~/.screenlayout/dock.sh
xrdb -merge ~/.Xresources &
feh --bg-scale /home/kisame/pictures/wallpapers/city.jpg &
urxvtd &
tint2 &
#nohup /home/kisame/.config/openbox/poly /home/kisame/.config/openbox &
